### ISSUE TITLE
shape error after some executions

### ISSUE THREAD

**Issue by alirazaee** [wangbm/MTCNN-Tensorflow#18]
Getting this error !
    .          .           .               .             .             .           .
   .          .           .            .            .             .            .
581 images done, pos: 9404 part: 25731 neg: 29047
581 images done, pos: 9404 part: 25731 neg: 29048
581 images done, pos: 9404 part: 25731 neg: 29049
581 images done, pos: 9404 part: 25731 neg: 29050
581 images done, pos: 9412 part: 25743 neg: 29050
581 images done, pos: 9412 part: 25751 neg: 29050
581 images done, pos: 9419 part: 25764 neg: 29050
581 images done, pos: 9424 part: 25779 neg: 29050
581 images done, pos: 9424 part: 25789 neg: 29050
Traceback (most recent call last):

  File "<ipython-input-2-9ba06a844f40>", line 1, in <module>
    runfile('E:/MTCNN-Tensorflow-master/prepare_data')

  File "C:\Users\alira\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\alira\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

MTCNN-Tensorflow-master/MTCNN-Tensorflow-master/prepare_data/gen_shuffle_data.py", line 163, in <module>
    main()

MTCNN-Tensorflow-master/MTCNN-Tensorflow-master/prepare_data/gen_shuffle_data.py", line 79, in main
    height, width, channel = img.shape

AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by nyingnying** [comment]
yes, i have the same problem too :(( T^T
please reply who already done the testing @wangbm

**Comment by fmoulita** [comment]
Haiii, i already done training size 12. 
also got this error before :
AttributeError: 'NoneType' object has no attribute 'shape'

It solved by check your wider face dataset, it need to be downloaded first. 
And if it is already downloaded, please check all those images need to be completed based on image list on 'wider_face_train.txt'

I also try using only one folder to make training more faster, and deleted all image list from folder 1 - 10.

please try, thanks
